#!/usr/bin/python3
from tkinter import Button, Entry, Frame, Label, Tk
from youtube_dl import YoutubeDL as ytdl


class app(Frame):
    def __init__(self, master):
        Frame.__init__(self, master)
        self.master.title('test')

        self.lbl = Label(self, text='enter the url')
        self.url = Entry(self)
        self.btn = Button(self, text='download', command=self.dl)

        self.url.focus()
        self.url.grid(row=1, columnspan=2, sticky='ew')
        self.lbl.grid(columnspan=2)
        self.grid()
        self.btn.grid(row=2, columnspan=2)

    def dl(self):
        opts = {
            'format': 'bestaudio/best',
            'postprocessors': [{
                'key': 'FFmpegExtractAudio',
                'preferredcodec': 'mp3',
            }]
        }
        ytdl(opts).download([self.url.get()])
        self.url.delete(0, 'end')


if __name__ == "__main__":
    root = Tk()
    app(root).pack(expand=True, fill='both')
    root.mainloop()
